version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.17
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            database: acai
            port: 5432
            schema: public
            user: ym
            password: ym
            migrations: false
            # rawAccess: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ym
      POSTGRES_PASSWORD: ym
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
