#endpoint: ''
endpoint: https://us1.prisma.sh/jae-chi/prismaLayer/dev
datamodel: datamodel.graphql

generate:
  - generator: javascript-client
    output: ./generated/prisma

hooks:
  post-deploy:
    - graphql get-schema --project database 
    - prisma generate