projects:
  database:
    schemaPath: schema/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
  app:
    schemaPath: schema/index.graphql
    extensions:
      endpoints:
        default: http://localhost:4000