endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.graphql

seed:
  run: babel-node seed.js

generate:
  - generator: javascript-client
    output: ./generated/prisma
  - generator: graphql-schema
    output: ../schema/generated/prisma.graphql

hooks:
  post-deploy:
    - graphql get-schema --project database 
    - prisma generate